export const UPDATE_ONBOARDING_STATUS = "UPDATE_ONBOARDING_STATUS";
export const UPDATE_USER_TOKEN = "UPDATE_USER_TOKEN";
export const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN";
export const UPDATE_USER_SIGNUP = "UPDATE_USER_SIGNUP";
export const UPDATE_USER_LOGOUT = "UPDATE_USER_LOGOUT";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
