export const UPDATE_ONBOARDING_STATUS = "UPDATE_ONBOARDING_STATUS";
export const UPDATE_USER_TOKEN = "UPDATE_USER_TOKEN";
export const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN";
export const UPDATE_USER_SIGNUP = "UPDATE_USER_SIGNUP";
export const UPDATE_USER_LOGOUT = "UPDATE_USER_LOGOUT";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const GET_LIST_CART = "GET_LIST_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";
export const DELETE_CART_ITEMS = "DELETE_CART_ITEMS";
export const DELETE_CART_ITEMS_FAILURE = "DELETE_CART_ITEMS_FAILURE";

export const BOOK_NOW = "BOOK_NOW";
export const GET_LIST_BOOKINGS = "GET_LIST_BOOKINGS";
export const GET_LIST_BOOKINGS_FAILURE = "GET_LIST_BOOKINGS_FAILURE";
export const UPDATE_CHECKOUT_DATA = "UPDATE_CHECKOUT_DATA";
